use lsp_types::request::GotoDefinition;

use crate::support::insta::test_transform_with_macros;

#[test]
fn generated_function() {
    test_transform_with_macros!(GotoDefinition, r#"
    #[complex_attribute_macro_v2]
    fn main() {
        let foobar = 123;
    }
    fn bar() {
        genera<caret>ted_function_v2();  // function generated by the attribute macro above
    }
    "#, @r"
    <sel>#[complex_attribute_macro_v2]</sel>
    fn main() {
        let foobar = 123;
    }
    fn bar() {
        generated_function_v2();  // function generated by the attribute macro above
    }
    ")
}
